
INSERT INTO USERS (NAME, EMAIL, IS_ACTIVE, CREATED_DATE, UPDATED_DATE) VALUES ('Test1', 'test1@test.com', 1, GETDATE(), GETDATE());
INSERT INTO USERS (NAME, EMAIL, IS_ACTIVE, CREATED_DATE, UPDATED_DATE) VALUES ('Test2', 'test1@test.com', 1, GETDATE(), GETDATE());
INSERT INTO USERS (NAME, EMAIL, IS_ACTIVE, CREATED_DATE, UPDATED_DATE) VALUES ('Test3', 'test1@test.com', 1, GETDATE(), GETDATE());
INSERT INTO USERS (NAME, EMAIL, IS_ACTIVE, CREATED_DATE, UPDATED_DATE) VALUES ('Test4', 'test1@test.com', 1, GETDATE(), GETDATE());
INSERT INTO USERS (NAME, EMAIL, IS_ACTIVE, CREATED_DATE, UPDATED_DATE) VALUES ('Test5', 'test1@test.com', 1, GETDATE(), GETDATE());
INSERT INTO USERS (NAME, EMAIL, IS_ACTIVE, CREATED_DATE, UPDATED_DATE) VALUES ('Test6', 'test1@test.com', 1, GETDATE(), GETDATE());
INSERT INTO USERS (NAME, EMAIL, IS_ACTIVE, CREATED_DATE, UPDATED_DATE) VALUES ('Test7', 'test1@test.com', 1, GETDATE(), GETDATE());
INSERT INTO USERS (NAME, EMAIL, IS_ACTIVE, CREATED_DATE, UPDATED_DATE) VALUES ('Test8', 'test1@test.com', 1, GETDATE(), GETDATE());
INSERT INTO USERS (NAME, EMAIL, IS_ACTIVE, CREATED_DATE, UPDATED_DATE) VALUES ('Test9', 'test1@test.com', 1, GETDATE(), GETDATE());
INSERT INTO USERS (NAME, EMAIL, IS_ACTIVE, CREATED_DATE, UPDATED_DATE) VALUES ('Test10', 'test1@test.com', 1, GETDATE(), GETDATE());


-- INSERT INTO ADDRESS(STREET, USER_ID ) VALUES ('STREET1', 1);